---
- hosts: all
  remote_user: pi
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    # basic packages installation ==============================================================
    - name: update package index
      apt: update_cache=yes
    - name: install basic packages
      apt: name={{item}} state=present
      with_items:
        - htop
        - sudo
        - tmux
        - mosh
        - iotop
        - vim
        - rsync
        - unzip
        - git
        - raspi-config
        - rpi-update
    - name: install dev requirements
      apt: name={{item}} state=present
      with_items:
        - gcc
        - make
        - python3
        - python3-pip
    - name: upgrade python pip
      command: easy_install3 -U pip

    # installation ============================================================================
    - name: install pigpio
      script: templates/install_pigpio.sh chdir=/home/pi/pigpio creates=/usr/local/bin/pigpiod

    - name: clone kati repo
      git: repo=git@github.com:techSU/kati.git dest=/home/pi/kati/ update=yes accept_hostkey=yes
      become: no
    - name: install kati python requirements
      pip: executable=pip3 requirements=/home/pi/kati/requirements.txt


    # service installation ====================================================================
    - name: install services
      template: src=templates/{{ item }}.service dest=/etc/systemd/system/ owner=root group=root mode=644
      notify:
        - reload systemd
      with_items:
        - pigpio
        - kati
    - meta: flush_handlers  # reload systemd now

    # service enabling ====================================================================
    - name: enable services
      command: systemctl enable {{ item }}
      # systemd: name={{ item }} state=reloaded enabled=yes daemon_reload=yes  # TODO wait for Ansible 2.2
      with_items:
        - pigpio
        - kati

    # service starting ====================================================================
    - name: start services
      command: systemctl restart {{ item }}
      with_items:
        - pigpio
        - kati

  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
