---
- hosts: all
  vars:
    ansible_ssh_user: root
  tasks:
    # basic packages
    - name: install basic packages
      apt: name={{item}} state=present
      with_items:
        - htop
        - sudo
        - tmux
        - mosh
        - iotop
        - vim
        - rsync
        - git
        - raspi-config
        - rpi-update
        - python
    - name: clone kati repo
      git: repo=git@github.com:techSU/kati.git dest=/root/kati/ update=yes
    # pigpio
    - name: kill pigpio daemon
      command: killall pigpiod
    - name: install pigpio
      command: /root/kati/deploy/install_pigpio.sh chdir=/root/pigpio/
    - name: start pigpio daemon
      command: pigpiod
